### ISSUE TITLE
Can't initialize blog

### ISSUE THREAD

**Issue by Sophivorus** [mspivak/gitblog#5]
Steps to reproduce:

1. Go to http://gitblog.link
2. Click the big button and grant GitBlog access to my GitHub account
3. Clone the repo with the command at https://gitblog.link/blogs/Sophivorus/sophivorus/posts/readme
4. Got the error below:

![image](https://user-images.githubusercontent.com/3542266/191622686-fa3ee86e-1310-408b-8452-12ba1e5c4acd.png)

**Comment by mspivak** [comment]
Hey @Sophivorus, this is most likely due the fact that you don't have your Github SSH keys setup. You can either:
- [Set them up](https://docs.github.com/en/authentication/connecting-to-github-with-ssh) 
- or use HTTPS instead: `git clone https://github.com/Sophivorus/sophivorus.git`

I am currently improving the `README.md` default blog post to show both methods and more. I'm also closing this issue, please feel free to re-open it if my answer wasn't successful. Happy gitblogging!
